// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/xmc-dev/xmc/xmc-core/proto/tasklist/tasklist.proto

/*
Package tasklist is a generated protocol buffer package.

It is generated from these files:
	github.com/xmc-dev/xmc/xmc-core/proto/tasklist/tasklist.proto

It has these top-level messages:
	TaskList
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	GetRequest
	GetResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
	ParticipateRequest
	ParticipateResponse
	CancelParticipationRequest
	CancelParticipationResponse
	GetParticipantsRequest
	GetParticipantsResponse
*/
package tasklist

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/wrappers"
import xmc_srv_core_tsrange "github.com/xmc-dev/xmc/xmc-core/proto/tsrange"
import xmc_srv_core_searchmeta "github.com/xmc-dev/xmc/xmc-core/proto/searchmeta"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskList struct {
	Id                 string                               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name               string                               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description        string                               `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	TimeRange          *xmc_srv_core_tsrange.TimestampRange `protobuf:"bytes,4,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	PageId             string                               `protobuf:"bytes,5,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	Title              string                               `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	PublicSubmissions  bool                                 `protobuf:"varint,7,opt,name=public_submissions,json=publicSubmissions" json:"public_submissions,omitempty"`
	Path               string                               `protobuf:"bytes,8,opt,name=path" json:"path,omitempty"`
	WithParticipations bool                                 `protobuf:"varint,9,opt,name=with_participations,json=withParticipations" json:"with_participations,omitempty"`
}

func (m *TaskList) Reset()                    { *m = TaskList{} }
func (m *TaskList) String() string            { return proto.CompactTextString(m) }
func (*TaskList) ProtoMessage()               {}
func (*TaskList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TaskList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskList) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskList) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *TaskList) GetTimeRange() *xmc_srv_core_tsrange.TimestampRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *TaskList) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *TaskList) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *TaskList) GetPublicSubmissions() bool {
	if m != nil {
		return m.PublicSubmissions
	}
	return false
}

func (m *TaskList) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *TaskList) GetWithParticipations() bool {
	if m != nil {
		return m.WithParticipations
	}
	return false
}

type CreateRequest struct {
	TaskList *TaskList `protobuf:"bytes,1,opt,name=task_list,json=taskList" json:"task_list,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetTaskList() *TaskList {
	if m != nil {
		return m.TaskList
	}
	return nil
}

type CreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	TaskList *TaskList `protobuf:"bytes,1,opt,name=task_list,json=taskList" json:"task_list,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetTaskList() *TaskList {
	if m != nil {
		return m.TaskList
	}
	return nil
}

type GetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResponse struct {
	TaskList *TaskList `protobuf:"bytes,1,opt,name=task_list,json=taskList" json:"task_list,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetResponse) GetTaskList() *TaskList {
	if m != nil {
		return m.TaskList
	}
	return nil
}

type UpdateRequest struct {
	Id                 string                               `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name               string                               `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Description        string                               `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	TimeRange          *xmc_srv_core_tsrange.TimestampRange `protobuf:"bytes,4,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	SetNullTime        bool                                 `protobuf:"varint,5,opt,name=set_null_time,json=setNullTime" json:"set_null_time,omitempty"`
	Title              string                               `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	PublicSubmissions  *google_protobuf.BoolValue           `protobuf:"bytes,7,opt,name=public_submissions,json=publicSubmissions" json:"public_submissions,omitempty"`
	WithParticipations *google_protobuf.BoolValue           `protobuf:"bytes,8,opt,name=with_participations,json=withParticipations" json:"with_participations,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRequest) GetTimeRange() *xmc_srv_core_tsrange.TimestampRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *UpdateRequest) GetSetNullTime() bool {
	if m != nil {
		return m.SetNullTime
	}
	return false
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateRequest) GetPublicSubmissions() *google_protobuf.BoolValue {
	if m != nil {
		return m.PublicSubmissions
	}
	return nil
}

func (m *UpdateRequest) GetWithParticipations() *google_protobuf.BoolValue {
	if m != nil {
		return m.WithParticipations
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteRequest struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	LeaveTasks bool   `protobuf:"varint,2,opt,name=leave_tasks,json=leaveTasks" json:"leave_tasks,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DeleteRequest) GetLeaveTasks() bool {
	if m != nil {
		return m.LeaveTasks
	}
	return false
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SearchRequest struct {
	Limit              uint32                               `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset             uint32                               `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	Name               string                               `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Description        string                               `protobuf:"bytes,4,opt,name=description" json:"description,omitempty"`
	TimeRange          *xmc_srv_core_tsrange.TimestampRange `protobuf:"bytes,5,opt,name=time_range,json=timeRange" json:"time_range,omitempty"`
	Title              string                               `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	IsPermanent        *google_protobuf.BoolValue           `protobuf:"bytes,7,opt,name=is_permanent,json=isPermanent" json:"is_permanent,omitempty"`
	PublicSubmissions  *google_protobuf.BoolValue           `protobuf:"bytes,8,opt,name=public_submissions,json=publicSubmissions" json:"public_submissions,omitempty"`
	WithParticipations *google_protobuf.BoolValue           `protobuf:"bytes,9,opt,name=with_participations,json=withParticipations" json:"with_participations,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SearchRequest) GetTimeRange() *xmc_srv_core_tsrange.TimestampRange {
	if m != nil {
		return m.TimeRange
	}
	return nil
}

func (m *SearchRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchRequest) GetIsPermanent() *google_protobuf.BoolValue {
	if m != nil {
		return m.IsPermanent
	}
	return nil
}

func (m *SearchRequest) GetPublicSubmissions() *google_protobuf.BoolValue {
	if m != nil {
		return m.PublicSubmissions
	}
	return nil
}

func (m *SearchRequest) GetWithParticipations() *google_protobuf.BoolValue {
	if m != nil {
		return m.WithParticipations
	}
	return nil
}

type SearchResponse struct {
	TaskLists []*TaskList                   `protobuf:"bytes,1,rep,name=task_lists,json=taskLists" json:"task_lists,omitempty"`
	Meta      *xmc_srv_core_searchmeta.Meta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SearchResponse) GetTaskLists() []*TaskList {
	if m != nil {
		return m.TaskLists
	}
	return nil
}

func (m *SearchResponse) GetMeta() *xmc_srv_core_searchmeta.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

type ParticipateRequest struct {
	TaskListId string `protobuf:"bytes,1,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *ParticipateRequest) Reset()                    { *m = ParticipateRequest{} }
func (m *ParticipateRequest) String() string            { return proto.CompactTextString(m) }
func (*ParticipateRequest) ProtoMessage()               {}
func (*ParticipateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ParticipateRequest) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type ParticipateResponse struct {
}

func (m *ParticipateResponse) Reset()                    { *m = ParticipateResponse{} }
func (m *ParticipateResponse) String() string            { return proto.CompactTextString(m) }
func (*ParticipateResponse) ProtoMessage()               {}
func (*ParticipateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type CancelParticipationRequest struct {
	TaskListId string `protobuf:"bytes,1,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *CancelParticipationRequest) Reset()                    { *m = CancelParticipationRequest{} }
func (m *CancelParticipationRequest) String() string            { return proto.CompactTextString(m) }
func (*CancelParticipationRequest) ProtoMessage()               {}
func (*CancelParticipationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

func (m *CancelParticipationRequest) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type CancelParticipationResponse struct {
}

func (m *CancelParticipationResponse) Reset()                    { *m = CancelParticipationResponse{} }
func (m *CancelParticipationResponse) String() string            { return proto.CompactTextString(m) }
func (*CancelParticipationResponse) ProtoMessage()               {}
func (*CancelParticipationResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

type GetParticipantsRequest struct {
	TaskListId string `protobuf:"bytes,1,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *GetParticipantsRequest) Reset()                    { *m = GetParticipantsRequest{} }
func (m *GetParticipantsRequest) String() string            { return proto.CompactTextString(m) }
func (*GetParticipantsRequest) ProtoMessage()               {}
func (*GetParticipantsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *GetParticipantsRequest) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type GetParticipantsResponse struct {
	UserIds []string `protobuf:"bytes,1,rep,name=user_ids,json=userIds" json:"user_ids,omitempty"`
}

func (m *GetParticipantsResponse) Reset()                    { *m = GetParticipantsResponse{} }
func (m *GetParticipantsResponse) String() string            { return proto.CompactTextString(m) }
func (*GetParticipantsResponse) ProtoMessage()               {}
func (*GetParticipantsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *GetParticipantsResponse) GetUserIds() []string {
	if m != nil {
		return m.UserIds
	}
	return nil
}

func init() {
	proto.RegisterType((*TaskList)(nil), "xmc.srv.core.tasklist.TaskList")
	proto.RegisterType((*CreateRequest)(nil), "xmc.srv.core.tasklist.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "xmc.srv.core.tasklist.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "xmc.srv.core.tasklist.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "xmc.srv.core.tasklist.ReadResponse")
	proto.RegisterType((*GetRequest)(nil), "xmc.srv.core.tasklist.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "xmc.srv.core.tasklist.GetResponse")
	proto.RegisterType((*UpdateRequest)(nil), "xmc.srv.core.tasklist.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "xmc.srv.core.tasklist.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "xmc.srv.core.tasklist.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "xmc.srv.core.tasklist.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "xmc.srv.core.tasklist.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "xmc.srv.core.tasklist.SearchResponse")
	proto.RegisterType((*ParticipateRequest)(nil), "xmc.srv.core.tasklist.ParticipateRequest")
	proto.RegisterType((*ParticipateResponse)(nil), "xmc.srv.core.tasklist.ParticipateResponse")
	proto.RegisterType((*CancelParticipationRequest)(nil), "xmc.srv.core.tasklist.CancelParticipationRequest")
	proto.RegisterType((*CancelParticipationResponse)(nil), "xmc.srv.core.tasklist.CancelParticipationResponse")
	proto.RegisterType((*GetParticipantsRequest)(nil), "xmc.srv.core.tasklist.GetParticipantsRequest")
	proto.RegisterType((*GetParticipantsResponse)(nil), "xmc.srv.core.tasklist.GetParticipantsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TaskListService service

type TaskListServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
	Participate(ctx context.Context, in *ParticipateRequest, opts ...client.CallOption) (*ParticipateResponse, error)
	CancelParticipation(ctx context.Context, in *CancelParticipationRequest, opts ...client.CallOption) (*CancelParticipationResponse, error)
	GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...client.CallOption) (*GetParticipantsResponse, error)
}

type taskListServiceClient struct {
	c           client.Client
	serviceName string
}

func NewTaskListServiceClient(serviceName string, c client.Client) TaskListServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "xmc.srv.core.tasklist"
	}
	return &taskListServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *taskListServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) Participate(ctx context.Context, in *ParticipateRequest, opts ...client.CallOption) (*ParticipateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.Participate", in)
	out := new(ParticipateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) CancelParticipation(ctx context.Context, in *CancelParticipationRequest, opts ...client.CallOption) (*CancelParticipationResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.CancelParticipation", in)
	out := new(CancelParticipationResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskListServiceClient) GetParticipants(ctx context.Context, in *GetParticipantsRequest, opts ...client.CallOption) (*GetParticipantsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskListService.GetParticipants", in)
	out := new(GetParticipantsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskListService service

type TaskListServiceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Get(context.Context, *GetRequest, *GetResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
	Participate(context.Context, *ParticipateRequest, *ParticipateResponse) error
	CancelParticipation(context.Context, *CancelParticipationRequest, *CancelParticipationResponse) error
	GetParticipants(context.Context, *GetParticipantsRequest, *GetParticipantsResponse) error
}

func RegisterTaskListServiceHandler(s server.Server, hdlr TaskListServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&TaskListService{hdlr}, opts...))
}

type TaskListService struct {
	TaskListServiceHandler
}

func (h *TaskListService) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.TaskListServiceHandler.Create(ctx, in, out)
}

func (h *TaskListService) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.TaskListServiceHandler.Read(ctx, in, out)
}

func (h *TaskListService) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.TaskListServiceHandler.Get(ctx, in, out)
}

func (h *TaskListService) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.TaskListServiceHandler.Update(ctx, in, out)
}

func (h *TaskListService) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.TaskListServiceHandler.Delete(ctx, in, out)
}

func (h *TaskListService) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TaskListServiceHandler.Search(ctx, in, out)
}

func (h *TaskListService) Participate(ctx context.Context, in *ParticipateRequest, out *ParticipateResponse) error {
	return h.TaskListServiceHandler.Participate(ctx, in, out)
}

func (h *TaskListService) CancelParticipation(ctx context.Context, in *CancelParticipationRequest, out *CancelParticipationResponse) error {
	return h.TaskListServiceHandler.CancelParticipation(ctx, in, out)
}

func (h *TaskListService) GetParticipants(ctx context.Context, in *GetParticipantsRequest, out *GetParticipantsResponse) error {
	return h.TaskListServiceHandler.GetParticipants(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/xmc-dev/xmc/xmc-core/proto/tasklist/tasklist.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 921 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x55, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0xee, 0xfe, 0x64, 0xe3, 0x3d, 0xce, 0xa6, 0x30, 0xe9, 0x8f, 0x31, 0x0a, 0x5d, 0x4c, 0x91,
	0x02, 0x52, 0xbc, 0xea, 0x82, 0xb8, 0x00, 0x5a, 0x41, 0x83, 0x14, 0x45, 0xfd, 0x51, 0x71, 0x0a,
	0x95, 0xb8, 0xb1, 0x66, 0xed, 0x93, 0xcd, 0xa8, 0xfe, 0xc3, 0x33, 0x4e, 0x7b, 0xc5, 0x0d, 0xcf,
	0xc2, 0x3b, 0xf0, 0x50, 0x5c, 0xf2, 0x00, 0xc8, 0x63, 0x8f, 0x77, 0xbd, 0xdd, 0x69, 0x96, 0x92,
	0x0b, 0xae, 0x3c, 0x33, 0xe7, 0x9c, 0xef, 0x78, 0xce, 0xf7, 0x9d, 0x33, 0x70, 0x7f, 0xce, 0xc4,
	0x79, 0x31, 0x73, 0x83, 0x34, 0x9e, 0xbc, 0x8e, 0x83, 0xc3, 0x10, 0x2f, 0xca, 0xaf, 0x5c, 0x07,
	0x69, 0x8e, 0x93, 0x2c, 0x4f, 0x45, 0x3a, 0x11, 0x94, 0xbf, 0x8c, 0x18, 0x17, 0xcd, 0xc2, 0x95,
	0xe7, 0xe4, 0xe6, 0xeb, 0x38, 0x70, 0x79, 0x7e, 0xe1, 0x96, 0xbe, 0xae, 0x32, 0xda, 0x1f, 0xcd,
	0xd3, 0x74, 0x1e, 0xd5, 0xc1, 0xb3, 0xe2, 0x6c, 0xf2, 0x2a, 0xa7, 0x59, 0x86, 0x39, 0xaf, 0xc2,
	0xec, 0x6f, 0x36, 0xcc, 0xca, 0x73, 0x9a, 0xcc, 0x51, 0x7d, 0xeb, 0xe0, 0xef, 0x37, 0x0b, 0xe6,
	0x48, 0xf3, 0xe0, 0x3c, 0x46, 0x41, 0x97, 0x96, 0x15, 0x84, 0xf3, 0x67, 0x17, 0x8c, 0xe7, 0x94,
	0xbf, 0x7c, 0xcc, 0xb8, 0x20, 0xbb, 0xd0, 0x65, 0xa1, 0xd5, 0x19, 0x77, 0x0e, 0x86, 0x5e, 0x97,
	0x85, 0x84, 0x40, 0x3f, 0xa1, 0x31, 0x5a, 0x5d, 0x79, 0x22, 0xd7, 0x64, 0x0c, 0x66, 0x88, 0x3c,
	0xc8, 0x59, 0x26, 0x58, 0x9a, 0x58, 0x3d, 0x69, 0x5a, 0x3e, 0x22, 0x47, 0x00, 0x82, 0xc5, 0xe8,
	0xcb, 0x3f, 0xb5, 0xfa, 0xe3, 0xce, 0x81, 0x39, 0xbd, 0xeb, 0xb6, 0xcb, 0x53, 0x5f, 0xe3, 0x39,
	0x8b, 0x91, 0x0b, 0x1a, 0x67, 0x5e, 0xb9, 0xf5, 0x86, 0x65, 0x9c, 0x5c, 0x92, 0xdb, 0xb0, 0x9d,
	0xd1, 0x39, 0xfa, 0x2c, 0xb4, 0xb6, 0x64, 0x8a, 0x41, 0xb9, 0x3d, 0x09, 0xc9, 0x0d, 0xd8, 0x12,
	0x4c, 0x44, 0x68, 0x0d, 0xe4, 0x71, 0xb5, 0x21, 0x87, 0x40, 0xb2, 0x62, 0x16, 0xb1, 0xc0, 0xe7,
	0xc5, 0x2c, 0x66, 0x9c, 0xb3, 0x34, 0xe1, 0xd6, 0xf6, 0xb8, 0x73, 0x60, 0x78, 0xef, 0x57, 0x96,
	0xd3, 0x85, 0xa1, 0xbc, 0x58, 0x46, 0xc5, 0xb9, 0x65, 0x54, 0x17, 0x2b, 0xd7, 0x64, 0x02, 0x7b,
	0xaf, 0x98, 0x38, 0xf7, 0x33, 0x9a, 0x0b, 0x16, 0xb0, 0x8c, 0x0a, 0x89, 0x31, 0x94, 0x18, 0xa4,
	0x34, 0x3d, 0x6b, 0x59, 0x9c, 0x27, 0x30, 0x3a, 0xca, 0x91, 0x0a, 0xf4, 0xf0, 0xd7, 0x02, 0xb9,
	0x20, 0xdf, 0xc2, 0xb0, 0xe4, 0xdd, 0x2f, 0x89, 0x97, 0x55, 0x34, 0xa7, 0x77, 0xdc, 0xb5, 0xb2,
	0x70, 0x55, 0xc9, 0x3d, 0x43, 0xd4, 0x2b, 0x67, 0x0c, 0xbb, 0x0a, 0x8e, 0x67, 0x69, 0xc2, 0x71,
	0x95, 0x0e, 0x67, 0x1f, 0x4c, 0x0f, 0x69, 0xa8, 0xd2, 0xad, 0x9a, 0x1f, 0xc3, 0x4e, 0x65, 0xae,
	0xc3, 0xff, 0xeb, 0xef, 0xc0, 0x31, 0x0a, 0x95, 0x4b, 0x29, 0xa1, 0xb3, 0x50, 0x82, 0xf3, 0x08,
	0x4c, 0xe9, 0x71, 0x25, 0xe9, 0xfe, 0xea, 0xc2, 0xe8, 0xa7, 0x2c, 0x5c, 0xaa, 0xe6, 0xff, 0x48,
	0x8c, 0x0e, 0x8c, 0x38, 0x0a, 0x3f, 0x29, 0xa2, 0xc8, 0x2f, 0x4f, 0xa5, 0x24, 0x0d, 0xcf, 0xe4,
	0x28, 0x9e, 0x16, 0x51, 0x54, 0x06, 0x6a, 0x74, 0x79, 0xa2, 0xd5, 0xa5, 0x39, 0xb5, 0xdd, 0x6a,
	0x36, 0xb8, 0x6a, 0x36, 0xb8, 0x0f, 0xd3, 0x34, 0xfa, 0x99, 0x46, 0x05, 0xae, 0xd3, 0xec, 0xa3,
	0xf5, 0xfa, 0x34, 0x2e, 0xc5, 0x5a, 0xa7, 0xdd, 0xf7, 0x60, 0x57, 0x55, 0xbb, 0xa2, 0xcf, 0xf9,
	0x0e, 0x46, 0x3f, 0x60, 0x84, 0xfa, 0xfa, 0xdf, 0x01, 0x33, 0x42, 0x7a, 0x81, 0x7e, 0xc9, 0x19,
	0x97, 0x34, 0x18, 0x1e, 0xc8, 0xa3, 0x92, 0x4f, 0x89, 0xa9, 0x10, 0x6a, 0xcc, 0x3f, 0x7a, 0x30,
	0x3a, 0x95, 0x13, 0x47, 0x81, 0xde, 0x80, 0xad, 0x88, 0xc5, 0xac, 0x12, 0xc8, 0xc8, 0xab, 0x36,
	0xe4, 0x16, 0x0c, 0xd2, 0xb3, 0x33, 0x8e, 0x42, 0xa2, 0x8e, 0xbc, 0x7a, 0xd7, 0x50, 0xde, 0xd3,
	0x53, 0xde, 0xbf, 0x8c, 0xf2, 0xad, 0x77, 0xa3, 0x7c, 0x3d, 0x9d, 0xf7, 0x61, 0x87, 0x71, 0x3f,
	0xc3, 0x3c, 0xa6, 0x09, 0x26, 0x62, 0x03, 0x22, 0x4d, 0xc6, 0x9f, 0x29, 0x77, 0x8d, 0x1a, 0x8c,
	0x2b, 0x54, 0xc3, 0xf0, 0x9d, 0xd4, 0xf0, 0x7b, 0x07, 0x76, 0x15, 0x4f, 0x75, 0x37, 0x3f, 0x00,
	0x68, 0xba, 0x99, 0x5b, 0x9d, 0x71, 0x6f, 0x93, 0x76, 0x1e, 0xaa, 0x76, 0xe6, 0xe4, 0x1e, 0xf4,
	0xcb, 0x57, 0x46, 0x12, 0x6a, 0x4e, 0xf7, 0xdb, 0x91, 0x4b, 0xaf, 0xd0, 0x13, 0x14, 0xd4, 0x93,
	0xae, 0xce, 0x57, 0x40, 0x16, 0xff, 0xd5, 0xc8, 0x70, 0x0c, 0x3b, 0xcd, 0x8f, 0xf8, 0x8d, 0x20,
	0x41, 0x65, 0x3a, 0x09, 0x9d, 0x9b, 0xb0, 0xd7, 0x8a, 0xab, 0xc5, 0xf7, 0x00, 0xec, 0x23, 0x9a,
	0x04, 0x18, 0xb5, 0x2e, 0xbb, 0x39, 0xec, 0x3e, 0x7c, 0xb8, 0x36, 0xbe, 0x86, 0xff, 0x1a, 0x6e,
	0x1d, 0xa3, 0x68, 0x6c, 0x89, 0xe0, 0x9b, 0x43, 0x7f, 0x09, 0xb7, 0xdf, 0x88, 0xad, 0xeb, 0xfe,
	0x01, 0x18, 0x05, 0xc7, 0xdc, 0x67, 0x61, 0x55, 0xf5, 0xa1, 0xb7, 0x5d, 0xee, 0x4f, 0x42, 0x3e,
	0xfd, 0x7b, 0x00, 0xd7, 0x55, 0xa9, 0x4f, 0x31, 0xbf, 0x60, 0x01, 0x92, 0x17, 0x30, 0xa8, 0x1e,
	0x0d, 0x72, 0x57, 0x43, 0x4e, 0xeb, 0x89, 0xb2, 0x3f, 0xbd, 0xc4, 0xab, 0xbe, 0xdc, 0x35, 0xf2,
	0x23, 0xf4, 0xcb, 0xc7, 0x84, 0x38, 0x9a, 0x80, 0xa5, 0x87, 0xc8, 0xfe, 0xe4, 0xad, 0x3e, 0x0d,
	0xe4, 0x53, 0xe8, 0x1d, 0xa3, 0x20, 0x1f, 0x6b, 0xbc, 0x17, 0xaf, 0x8d, 0xed, 0xbc, 0xcd, 0xa5,
	0xc1, 0x7b, 0x01, 0x83, 0x6a, 0x86, 0x69, 0xef, 0xde, 0x7a, 0x50, 0xb4, 0x77, 0x5f, 0x19, 0x84,
	0x12, 0xb8, 0x1a, 0x64, 0x5a, 0xe0, 0xd6, 0xa4, 0xd4, 0x02, 0xaf, 0x4c, 0x43, 0x09, 0x5c, 0xb5,
	0x99, 0x16, 0xb8, 0x35, 0x2d, 0xb5, 0xc0, 0xed, 0x5e, 0x75, 0xae, 0x91, 0x33, 0x30, 0x97, 0x5a,
	0x80, 0x7c, 0xa6, 0x89, 0x7b, 0xb3, 0xbd, 0xec, 0xcf, 0x37, 0x71, 0x6d, 0xf2, 0xfc, 0x06, 0x7b,
	0x6b, 0x7a, 0x82, 0xdc, 0xd3, 0xa9, 0x4a, 0xdb, 0x7f, 0xf6, 0xf4, 0xdf, 0x84, 0x34, 0xf9, 0x73,
	0xb8, 0xbe, 0xd2, 0x38, 0xe4, 0x50, 0xaf, 0x95, 0x35, 0xcd, 0x69, 0xbb, 0x9b, 0xba, 0xab, 0x9c,
	0x0f, 0xe1, 0x17, 0x43, 0x79, 0xcd, 0x06, 0x72, 0xa0, 0x7e, 0xf1, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x36, 0x8b, 0x80, 0x8d, 0x2c, 0x0c, 0x00, 0x00,
}
