// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/xmc-dev/xmc/xmc-core/proto/submission/submission.proto

/*
Package submission is a generated protocol buffer package.

It is generated from these files:
	github.com/xmc-dev/xmc/xmc-core/proto/submission/submission.proto

It has these top-level messages:
	StateValue
	Submission
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package submission

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import xmc_srv_core_result "github.com/xmc-dev/xmc/xmc-core/proto/result"
import xmc_srv_core_searchmeta "github.com/xmc-dev/xmc/xmc-core/proto/searchmeta"
import xmc_srv_core_tsrange "github.com/xmc-dev/xmc/xmc-core/proto/tsrange"
import xmc_srv_dispatcher_job "github.com/xmc-dev/xmc/dispatcher-srv/proto/job"
import google_protobuf1 "github.com/golang/protobuf/ptypes/timestamp"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type State int32

const (
	State_WAITING    State = 0
	State_PROCESSING State = 1
	State_DONE       State = 2
)

var State_name = map[int32]string{
	0: "WAITING",
	1: "PROCESSING",
	2: "DONE",
}
var State_value = map[string]int32{
	"WAITING":    0,
	"PROCESSING": 1,
	"DONE":       2,
}

func (x State) String() string {
	return proto.EnumName(State_name, int32(x))
}
func (State) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type StateValue struct {
	Value State `protobuf:"varint,1,opt,name=value,enum=xmc.srv.core.submission.State" json:"value,omitempty"`
}

func (m *StateValue) Reset()                    { *m = StateValue{} }
func (m *StateValue) String() string            { return proto.CompactTextString(m) }
func (*StateValue) ProtoMessage()               {}
func (*StateValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StateValue) GetValue() State {
	if m != nil {
		return m.Value
	}
	return State_WAITING
}

type Submission struct {
	Id           string                      `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	TaskId       string                      `protobuf:"bytes,2,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	DatasetId    string                      `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	AttachmentId string                      `protobuf:"bytes,4,opt,name=attachment_id,json=attachmentId" json:"attachment_id,omitempty"`
	EvalId       string                      `protobuf:"bytes,5,opt,name=eval_id,json=evalId" json:"eval_id,omitempty"`
	Result       *xmc_srv_core_result.Result `protobuf:"bytes,6,opt,name=result" json:"result,omitempty"`
	CreatedAt    *google_protobuf1.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	FinishedAt   *google_protobuf1.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	State        State                       `protobuf:"varint,9,opt,name=state,enum=xmc.srv.core.submission.State" json:"state,omitempty"`
	Language     string                      `protobuf:"bytes,10,opt,name=language" json:"language,omitempty"`
	BuildCommand string                      `protobuf:"bytes,11,opt,name=build_command,json=buildCommand" json:"build_command,omitempty"`
	UserId       string                      `protobuf:"bytes,12,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Censored     bool                        `protobuf:"varint,13,opt,name=censored" json:"censored,omitempty"`
}

func (m *Submission) Reset()                    { *m = Submission{} }
func (m *Submission) String() string            { return proto.CompactTextString(m) }
func (*Submission) ProtoMessage()               {}
func (*Submission) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Submission) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Submission) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Submission) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *Submission) GetAttachmentId() string {
	if m != nil {
		return m.AttachmentId
	}
	return ""
}

func (m *Submission) GetEvalId() string {
	if m != nil {
		return m.EvalId
	}
	return ""
}

func (m *Submission) GetResult() *xmc_srv_core_result.Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *Submission) GetCreatedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Submission) GetFinishedAt() *google_protobuf1.Timestamp {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

func (m *Submission) GetState() State {
	if m != nil {
		return m.State
	}
	return State_WAITING
}

func (m *Submission) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Submission) GetBuildCommand() string {
	if m != nil {
		return m.BuildCommand
	}
	return ""
}

func (m *Submission) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Submission) GetCensored() bool {
	if m != nil {
		return m.Censored
	}
	return false
}

type CreateRequest struct {
	TaskId   string `protobuf:"bytes,1,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	Code     []byte `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Language string `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *CreateRequest) GetCode() []byte {
	if m != nil {
		return m.Code
	}
	return nil
}

func (m *CreateRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

type CreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id                 string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	IncludeResult      bool   `protobuf:"varint,2,opt,name=include_result,json=includeResult" json:"include_result,omitempty"`
	IncludeTestResults bool   `protobuf:"varint,3,opt,name=include_test_results,json=includeTestResults" json:"include_test_results,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ReadRequest) GetIncludeResult() bool {
	if m != nil {
		return m.IncludeResult
	}
	return false
}

func (m *ReadRequest) GetIncludeTestResults() bool {
	if m != nil {
		return m.IncludeTestResults
	}
	return false
}

type ReadResponse struct {
	Submission *Submission `protobuf:"bytes,1,opt,name=submission" json:"submission,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ReadResponse) GetSubmission() *Submission {
	if m != nil {
		return m.Submission
	}
	return nil
}

type UpdateRequest struct {
	Job *xmc_srv_dispatcher_job.Job `protobuf:"bytes,1,opt,name=job" json:"job,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UpdateRequest) GetJob() *xmc_srv_dispatcher_job.Job {
	if m != nil {
		return m.Job
	}
	return nil
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type SearchRequest struct {
	Limit              uint32                               `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset             uint32                               `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	TaskId             string                               `protobuf:"bytes,3,opt,name=task_id,json=taskId" json:"task_id,omitempty"`
	DatasetId          string                               `protobuf:"bytes,4,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	EvalId             string                               `protobuf:"bytes,5,opt,name=eval_id,json=evalId" json:"eval_id,omitempty"`
	State              *StateValue                          `protobuf:"bytes,6,opt,name=state" json:"state,omitempty"`
	Language           string                               `protobuf:"bytes,7,opt,name=language" json:"language,omitempty"`
	CreatedAt          *xmc_srv_core_tsrange.TimestampRange `protobuf:"bytes,8,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	FinishedAt         *xmc_srv_core_tsrange.TimestampRange `protobuf:"bytes,9,opt,name=finished_at,json=finishedAt" json:"finished_at,omitempty"`
	ErrorMessage       string                               `protobuf:"bytes,10,opt,name=error_message,json=errorMessage" json:"error_message,omitempty"`
	CompilationMessage string                               `protobuf:"bytes,11,opt,name=compilation_message,json=compilationMessage" json:"compilation_message,omitempty"`
	IncludeResult      bool                                 `protobuf:"varint,12,opt,name=include_result,json=includeResult" json:"include_result,omitempty"`
	IncludeTestResults bool                                 `protobuf:"varint,13,opt,name=include_test_results,json=includeTestResults" json:"include_test_results,omitempty"`
	UserId             string                               `protobuf:"bytes,14,opt,name=user_id,json=userId" json:"user_id,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *SearchRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchRequest) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *SearchRequest) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *SearchRequest) GetEvalId() string {
	if m != nil {
		return m.EvalId
	}
	return ""
}

func (m *SearchRequest) GetState() *StateValue {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *SearchRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SearchRequest) GetCreatedAt() *xmc_srv_core_tsrange.TimestampRange {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *SearchRequest) GetFinishedAt() *xmc_srv_core_tsrange.TimestampRange {
	if m != nil {
		return m.FinishedAt
	}
	return nil
}

func (m *SearchRequest) GetErrorMessage() string {
	if m != nil {
		return m.ErrorMessage
	}
	return ""
}

func (m *SearchRequest) GetCompilationMessage() string {
	if m != nil {
		return m.CompilationMessage
	}
	return ""
}

func (m *SearchRequest) GetIncludeResult() bool {
	if m != nil {
		return m.IncludeResult
	}
	return false
}

func (m *SearchRequest) GetIncludeTestResults() bool {
	if m != nil {
		return m.IncludeTestResults
	}
	return false
}

func (m *SearchRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type SearchResponse struct {
	Submissions []*Submission                 `protobuf:"bytes,1,rep,name=submissions" json:"submissions,omitempty"`
	Meta        *xmc_srv_core_searchmeta.Meta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchResponse) GetSubmissions() []*Submission {
	if m != nil {
		return m.Submissions
	}
	return nil
}

func (m *SearchResponse) GetMeta() *xmc_srv_core_searchmeta.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*StateValue)(nil), "xmc.srv.core.submission.StateValue")
	proto.RegisterType((*Submission)(nil), "xmc.srv.core.submission.Submission")
	proto.RegisterType((*CreateRequest)(nil), "xmc.srv.core.submission.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "xmc.srv.core.submission.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "xmc.srv.core.submission.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "xmc.srv.core.submission.ReadResponse")
	proto.RegisterType((*UpdateRequest)(nil), "xmc.srv.core.submission.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "xmc.srv.core.submission.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "xmc.srv.core.submission.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "xmc.srv.core.submission.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "xmc.srv.core.submission.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "xmc.srv.core.submission.SearchResponse")
	proto.RegisterEnum("xmc.srv.core.submission.State", State_name, State_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for SubmissionService service

type SubmissionServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type submissionServiceClient struct {
	c           client.Client
	serviceName string
}

func NewSubmissionServiceClient(serviceName string, c client.Client) SubmissionServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "xmc.srv.core.submission"
	}
	return &submissionServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *submissionServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SubmissionService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SubmissionService.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SubmissionService.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SubmissionService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *submissionServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "SubmissionService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SubmissionService service

type SubmissionServiceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterSubmissionServiceHandler(s server.Server, hdlr SubmissionServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&SubmissionService{hdlr}, opts...))
}

type SubmissionService struct {
	SubmissionServiceHandler
}

func (h *SubmissionService) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.SubmissionServiceHandler.Create(ctx, in, out)
}

func (h *SubmissionService) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.SubmissionServiceHandler.Read(ctx, in, out)
}

func (h *SubmissionService) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.SubmissionServiceHandler.Update(ctx, in, out)
}

func (h *SubmissionService) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.SubmissionServiceHandler.Delete(ctx, in, out)
}

func (h *SubmissionService) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.SubmissionServiceHandler.Search(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/xmc-dev/xmc/xmc-core/proto/submission/submission.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 947 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xed, 0x8e, 0xdb, 0x44,
	0x14, 0xdd, 0x7c, 0x6c, 0x36, 0xb9, 0x89, 0xa3, 0x65, 0xa8, 0xa8, 0x15, 0x54, 0x1a, 0x79, 0x5b,
	0x58, 0x21, 0xad, 0x03, 0x29, 0x7f, 0x56, 0x95, 0x90, 0xb6, 0xe9, 0x0a, 0x05, 0xa9, 0x2d, 0x72,
	0xb6, 0x80, 0xe8, 0x8f, 0x68, 0xe2, 0x99, 0xcd, 0x4e, 0xb1, 0x3d, 0xc1, 0x33, 0x8e, 0xfa, 0x0c,
	0xbc, 0x11, 0x2f, 0xc3, 0x0b, 0xf0, 0x12, 0x68, 0x3e, 0x1c, 0xdb, 0x81, 0x64, 0xd3, 0x1f, 0x91,
	0xe7, 0xe3, 0xde, 0x93, 0xeb, 0x73, 0xef, 0x39, 0x86, 0xab, 0x25, 0x93, 0x77, 0xd9, 0xc2, 0x0f,
	0x79, 0x3c, 0xfa, 0x10, 0x87, 0x17, 0x84, 0xae, 0xd5, 0x53, 0xaf, 0x43, 0x9e, 0xd2, 0xd1, 0x2a,
	0xe5, 0x92, 0x8f, 0x44, 0xb6, 0x88, 0x99, 0x10, 0x8c, 0x27, 0xa5, 0xa5, 0xaf, 0xef, 0xd0, 0xc3,
	0x0f, 0x71, 0xe8, 0x8b, 0x74, 0xed, 0xab, 0x78, 0xbf, 0xb8, 0x1e, 0x5c, 0x1e, 0x86, 0x9d, 0x52,
	0x91, 0x45, 0xd2, 0x3e, 0x0c, 0xe6, 0xe0, 0xd0, 0xb2, 0x28, 0x4e, 0xc3, 0xbb, 0x98, 0x4a, 0x5c,
	0x5a, 0x5a, 0x88, 0xe7, 0x87, 0x41, 0x48, 0x91, 0xe2, 0x64, 0x49, 0xf3, 0xa7, 0x4d, 0xde, 0x55,
	0x3a, 0x61, 0x62, 0x85, 0x65, 0x78, 0x47, 0xd3, 0x0b, 0x91, 0xae, 0x2d, 0xc4, 0x7b, 0xbe, 0x50,
	0x3f, 0x9b, 0xfa, 0x78, 0xc9, 0xf9, 0x32, 0xb2, 0xf0, 0x8b, 0xec, 0x76, 0x24, 0x59, 0x4c, 0x85,
	0xc4, 0xf1, 0xca, 0x04, 0x78, 0x2f, 0x00, 0x66, 0x12, 0x4b, 0xfa, 0x33, 0x8e, 0x32, 0x8a, 0xbe,
	0x83, 0xe3, 0xb5, 0x5a, 0xb8, 0xb5, 0x61, 0xed, 0xbc, 0x3f, 0xfe, 0xc2, 0xdf, 0xc1, 0xa6, 0xaf,
	0x73, 0x02, 0x13, 0xec, 0xfd, 0xd3, 0x00, 0x98, 0x6d, 0xee, 0x50, 0x1f, 0xea, 0x8c, 0x68, 0x84,
	0x4e, 0x50, 0x67, 0x04, 0x3d, 0x84, 0x13, 0x89, 0xc5, 0xef, 0x73, 0x46, 0xdc, 0xba, 0x3e, 0x6c,
	0xa9, 0xed, 0x94, 0xa0, 0x47, 0x00, 0x04, 0x4b, 0x2c, 0xa8, 0x54, 0x77, 0x0d, 0x7d, 0xd7, 0xb1,
	0x27, 0x53, 0x82, 0xce, 0xc0, 0xc1, 0x52, 0x62, 0xc5, 0x63, 0xa2, 0x23, 0x9a, 0x3a, 0xa2, 0x57,
	0x1c, 0x4e, 0x35, 0x38, 0x5d, 0xe3, 0x48, 0x5d, 0x1f, 0x1b, 0x70, 0xb5, 0x9d, 0x12, 0xf4, 0x0c,
	0x5a, 0xa6, 0x89, 0x6e, 0x6b, 0x58, 0x3b, 0xef, 0x8e, 0x3f, 0xaf, 0xbe, 0x8b, 0x6d, 0x70, 0xa0,
	0x1f, 0x81, 0x0d, 0x45, 0x97, 0x00, 0x61, 0x4a, 0xb1, 0xa4, 0x64, 0x8e, 0xa5, 0x7b, 0xa2, 0x13,
	0x07, 0xbe, 0xe1, 0xd0, 0xcf, 0x39, 0xf4, 0x6f, 0x72, 0x0e, 0x83, 0x8e, 0x8d, 0xbe, 0x92, 0xe8,
	0x39, 0x74, 0x6f, 0x59, 0xc2, 0xc4, 0x9d, 0xc9, 0x6d, 0xdf, 0x9b, 0x0b, 0x79, 0xf8, 0x95, 0x54,
	0xbc, 0x0b, 0xc5, 0xa8, 0xdb, 0x39, 0x8c, 0x77, 0x1d, 0x8c, 0x06, 0xd0, 0x8e, 0x70, 0xb2, 0xcc,
	0xf0, 0x92, 0xba, 0xa0, 0x5f, 0x7e, 0xb3, 0x57, 0xe4, 0x2d, 0x32, 0x16, 0x91, 0x79, 0xc8, 0xe3,
	0x18, 0x27, 0xc4, 0xed, 0x1a, 0xf2, 0xf4, 0xe1, 0xc4, 0x9c, 0x29, 0xf2, 0x32, 0x41, 0x53, 0x45,
	0x5e, 0xcf, 0x90, 0xa7, 0xb6, 0x53, 0xa2, 0x90, 0x43, 0x9a, 0x08, 0x9e, 0x52, 0xe2, 0x3a, 0xc3,
	0xda, 0x79, 0x3b, 0xd8, 0xec, 0xbd, 0x5f, 0xc1, 0x99, 0xe8, 0xb7, 0x0e, 0xe8, 0x1f, 0x19, 0x15,
	0xb2, 0xdc, 0xdf, 0x5a, 0xa5, 0xbf, 0x08, 0x9a, 0x21, 0x27, 0x54, 0x77, 0xbd, 0x17, 0xe8, 0x75,
	0xa5, 0xe6, 0x46, 0xb5, 0x66, 0x6f, 0x08, 0xfd, 0x1c, 0x59, 0xac, 0x78, 0x22, 0xe8, 0xf6, 0x28,
	0x79, 0x6b, 0xe8, 0x06, 0x14, 0x93, 0xfc, 0x9f, 0xb7, 0x27, 0xed, 0x29, 0xf4, 0x59, 0x12, 0x46,
	0x19, 0xa1, 0x73, 0xdb, 0xfb, 0xba, 0x2e, 0xde, 0xb1, 0xa7, 0xa6, 0xdb, 0xe8, 0x1b, 0x78, 0x90,
	0x87, 0x49, 0x2a, 0xa4, 0x8d, 0x15, 0xba, 0x9e, 0x76, 0x80, 0xec, 0xdd, 0x0d, 0x15, 0xd2, 0x24,
	0x08, 0x6f, 0x06, 0x3d, 0xf3, 0xbf, 0xb6, 0xae, 0x09, 0x40, 0xd1, 0x14, 0x5d, 0x40, 0x77, 0x7c,
	0xb6, 0xbb, 0x69, 0x9b, 0x65, 0x50, 0x4a, 0xf3, 0xbe, 0x07, 0xe7, 0xed, 0x8a, 0x94, 0x88, 0xbc,
	0x80, 0xc6, 0x7b, 0xbe, 0xb0, 0x70, 0xc5, 0xbc, 0x16, 0x32, 0xf7, 0x95, 0xb0, 0x7f, 0xe4, 0x8b,
	0x40, 0xc5, 0x79, 0xa7, 0xd0, 0xcf, 0xf3, 0x4d, 0x59, 0xde, 0x63, 0x70, 0x5e, 0xd2, 0x88, 0x16,
	0x88, 0xdb, 0xfc, 0x9d, 0x42, 0x3f, 0x0f, 0xb0, 0x29, 0x7f, 0x35, 0xc1, 0x99, 0x69, 0xb7, 0xca,
	0x73, 0x1e, 0xc0, 0x71, 0xc4, 0x62, 0x26, 0x75, 0x9a, 0x13, 0x98, 0x0d, 0xfa, 0x0c, 0x5a, 0xfc,
	0xf6, 0x56, 0x50, 0x43, 0xa9, 0x13, 0xd8, 0x5d, 0xb9, 0xf9, 0x8d, 0x3d, 0xe2, 0x6e, 0x6e, 0x8b,
	0x7b, 0xa7, 0x6e, 0x2f, 0x73, 0x29, 0xb4, 0xee, 0x63, 0x75, 0x63, 0x5b, 0xff, 0xa7, 0x87, 0x93,
	0x2d, 0x3d, 0x4c, 0x2a, 0xca, 0x36, 0xea, 0x7c, 0x52, 0xc5, 0xce, 0x4d, 0xb7, 0x90, 0xa8, 0xda,
	0x96, 0x35, 0x7e, 0x5d, 0xd5, 0x78, 0xe7, 0x23, 0x50, 0xca, 0x6a, 0x3f, 0x03, 0x87, 0xa6, 0x29,
	0x4f, 0xe7, 0x31, 0x15, 0xa2, 0x10, 0x6f, 0x4f, 0x1f, 0xbe, 0x32, 0x67, 0x68, 0x04, 0x9f, 0x86,
	0x3c, 0x5e, 0xb1, 0x08, 0x4b, 0xc6, 0x93, 0x4d, 0xa8, 0x91, 0x31, 0x2a, 0x5d, 0xe5, 0x09, 0xff,
	0x1d, 0xfe, 0xde, 0xc7, 0x0c, 0xbf, 0xb3, 0x6b, 0xf8, 0xcb, 0x2e, 0xd1, 0x2f, 0xbb, 0x84, 0xf7,
	0x67, 0x0d, 0xfa, 0xf9, 0xec, 0x58, 0x61, 0x5c, 0x43, 0xb7, 0x68, 0x91, 0x70, 0x6b, 0xc3, 0xc6,
	0xa1, 0xca, 0x28, 0xe7, 0xa1, 0x6f, 0xa1, 0xa9, 0x3e, 0x9e, 0x7a, 0xd6, 0xba, 0xe3, 0x47, 0x5b,
	0xf9, 0xc5, 0xc7, 0xf5, 0x15, 0x95, 0x38, 0xd0, 0xa1, 0x5f, 0xfb, 0x70, 0xac, 0x27, 0x02, 0x75,
	0xe1, 0xe4, 0x97, 0xab, 0xe9, 0xcd, 0xf4, 0xf5, 0x0f, 0xa7, 0x47, 0xa8, 0x0f, 0xf0, 0x53, 0xf0,
	0x66, 0x72, 0x3d, 0x9b, 0xa9, 0x7d, 0x0d, 0xb5, 0xa1, 0xf9, 0xf2, 0xcd, 0xeb, 0xeb, 0xd3, 0xfa,
	0xf8, 0xef, 0x06, 0x7c, 0x52, 0xfc, 0xfd, 0x8c, 0xa6, 0x6b, 0x16, 0x52, 0xf4, 0x0e, 0x5a, 0xc6,
	0x82, 0xd0, 0x97, 0x3b, 0x8b, 0xae, 0xb8, 0xdf, 0xe0, 0xab, 0x7b, 0xe3, 0xac, 0xd2, 0x8e, 0xd0,
	0x5b, 0x68, 0x2a, 0x17, 0x41, 0x4f, 0x76, 0xa6, 0x94, 0xcc, 0x6d, 0xf0, 0xf4, 0x9e, 0xa8, 0x0d,
	0xec, 0x3b, 0x68, 0x19, 0x1f, 0xd8, 0x53, 0x73, 0xc5, 0x68, 0xf6, 0xd4, 0xbc, 0x65, 0x28, 0x1a,
	0xdc, 0x38, 0xc6, 0x1e, 0xf0, 0x8a, 0xe7, 0xec, 0x01, 0xdf, 0xb2, 0x1e, 0x0d, 0x6e, 0xe6, 0x67,
	0x0f, 0x78, 0xc5, 0x9c, 0xf6, 0x80, 0x57, 0x07, 0xd1, 0x3b, 0x7a, 0xd1, 0xfb, 0xad, 0x64, 0xb6,
	0x8b, 0x96, 0xfe, 0x02, 0x3f, 0xfb, 0x37, 0x00, 0x00, 0xff, 0xff, 0x86, 0x6d, 0x53, 0x22, 0x63,
	0x0a, 0x00, 0x00,
}
