FROM golang:alpine as builder

WORKDIR /go/src/github.com/xmc-dev/xmc/auth-srv

COPY . ../

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo .

FROM alpine:latest

RUN apk --no-cache add ca-certificates

RUN mkdir /app
WORKDIR /app
COPY --from=builder /go/src/github.com/xmc-dev/xmc/auth-srv/auth-srv .
COPY --from=builder /go/src/github.com/xmc-dev/xmc/auth-srv/static ./static

CMD ["./auth-srv", "--registry", "xmcconsul"]
