language: go
sudo: false

before_install:
  - wget 'https://releases.hashicorp.com/consul/1.0.7/consul_1.0.7_linux_amd64.zip'
  - unzip consul_1.0.7_linux_amd64.zip
  - mkdir consul_dir
  - chmod +x consul
  - mkdir -p ~/.local/bin
  - mv ./consul ~/.local/bin/consul

script:
  -  go test -race -coverprofile=coverage.txt -covermode=atomic -v ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
