// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/xmc-dev/xmc/xmc-core/proto/task/task.proto

/*
Package task is a generated protocol buffer package.

It is generated from these files:
	github.com/xmc-dev/xmc/xmc-core/proto/task/task.proto

It has these top-level messages:
	Task
	CreateRequest
	CreateResponse
	ReadRequest
	ReadResponse
	GetRequest
	GetResponse
	UpdateRequest
	UpdateResponse
	DeleteRequest
	DeleteResponse
	SearchRequest
	SearchResponse
*/
package task

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import xmc_srv_core_searchmeta "github.com/xmc-dev/xmc/xmc-core/proto/searchmeta"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Task struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DatasetId   string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	InputFile   string `protobuf:"bytes,5,opt,name=input_file,json=inputFile" json:"input_file,omitempty"`
	OutputFile  string `protobuf:"bytes,6,opt,name=output_file,json=outputFile" json:"output_file,omitempty"`
	PageId      string `protobuf:"bytes,7,opt,name=page_id,json=pageId" json:"page_id,omitempty"`
	Title       string `protobuf:"bytes,8,opt,name=title" json:"title,omitempty"`
	TaskListId  string `protobuf:"bytes,9,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *Task) Reset()                    { *m = Task{} }
func (m *Task) String() string            { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()               {}
func (*Task) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Task) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Task) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *Task) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Task) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Task) GetInputFile() string {
	if m != nil {
		return m.InputFile
	}
	return ""
}

func (m *Task) GetOutputFile() string {
	if m != nil {
		return m.OutputFile
	}
	return ""
}

func (m *Task) GetPageId() string {
	if m != nil {
		return m.PageId
	}
	return ""
}

func (m *Task) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Task) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type CreateRequest struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *CreateRequest) Reset()                    { *m = CreateRequest{} }
func (m *CreateRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateRequest) ProtoMessage()               {}
func (*CreateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreateRequest) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type CreateResponse struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *CreateResponse) Reset()                    { *m = CreateResponse{} }
func (m *CreateResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateResponse) ProtoMessage()               {}
func (*CreateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CreateResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ReadRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReadResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type GetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetResponse struct {
	Task *Task `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetResponse) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

type UpdateRequest struct {
	Id          string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	DatasetId   string `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description" json:"description,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	InputFile   string `protobuf:"bytes,5,opt,name=input_file,json=inputFile" json:"input_file,omitempty"`
	OutputFile  string `protobuf:"bytes,6,opt,name=output_file,json=outputFile" json:"output_file,omitempty"`
	Title       string `protobuf:"bytes,7,opt,name=title" json:"title,omitempty"`
	TaskListId  string `protobuf:"bytes,8,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *UpdateRequest) Reset()                    { *m = UpdateRequest{} }
func (m *UpdateRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateRequest) ProtoMessage()               {}
func (*UpdateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UpdateRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateRequest) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *UpdateRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateRequest) GetInputFile() string {
	if m != nil {
		return m.InputFile
	}
	return ""
}

func (m *UpdateRequest) GetOutputFile() string {
	if m != nil {
		return m.OutputFile
	}
	return ""
}

func (m *UpdateRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateRequest) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type UpdateResponse struct {
}

func (m *UpdateResponse) Reset()                    { *m = UpdateResponse{} }
func (m *UpdateResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateResponse) ProtoMessage()               {}
func (*UpdateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteRequest) Reset()                    { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()               {}
func (*DeleteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteResponse struct {
}

func (m *DeleteResponse) Reset()                    { *m = DeleteResponse{} }
func (m *DeleteResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteResponse) ProtoMessage()               {}
func (*DeleteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

type SearchRequest struct {
	Limit       uint32 `protobuf:"varint,1,opt,name=limit" json:"limit,omitempty"`
	Offset      uint32 `protobuf:"varint,2,opt,name=offset" json:"offset,omitempty"`
	DatasetId   string `protobuf:"bytes,3,opt,name=dataset_id,json=datasetId" json:"dataset_id,omitempty"`
	Name        string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Description string `protobuf:"bytes,5,opt,name=description" json:"description,omitempty"`
	Title       string `protobuf:"bytes,6,opt,name=title" json:"title,omitempty"`
	TaskListId  string `protobuf:"bytes,7,opt,name=task_list_id,json=taskListId" json:"task_list_id,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *SearchRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *SearchRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SearchRequest) GetDatasetId() string {
	if m != nil {
		return m.DatasetId
	}
	return ""
}

func (m *SearchRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SearchRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SearchRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *SearchRequest) GetTaskListId() string {
	if m != nil {
		return m.TaskListId
	}
	return ""
}

type SearchResponse struct {
	Tasks []*Task                       `protobuf:"bytes,1,rep,name=tasks" json:"tasks,omitempty"`
	Meta  *xmc_srv_core_searchmeta.Meta `protobuf:"bytes,2,opt,name=meta" json:"meta,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *SearchResponse) GetTasks() []*Task {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *SearchResponse) GetMeta() *xmc_srv_core_searchmeta.Meta {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Task)(nil), "xmc.srv.core.task.Task")
	proto.RegisterType((*CreateRequest)(nil), "xmc.srv.core.task.CreateRequest")
	proto.RegisterType((*CreateResponse)(nil), "xmc.srv.core.task.CreateResponse")
	proto.RegisterType((*ReadRequest)(nil), "xmc.srv.core.task.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "xmc.srv.core.task.ReadResponse")
	proto.RegisterType((*GetRequest)(nil), "xmc.srv.core.task.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "xmc.srv.core.task.GetResponse")
	proto.RegisterType((*UpdateRequest)(nil), "xmc.srv.core.task.UpdateRequest")
	proto.RegisterType((*UpdateResponse)(nil), "xmc.srv.core.task.UpdateResponse")
	proto.RegisterType((*DeleteRequest)(nil), "xmc.srv.core.task.DeleteRequest")
	proto.RegisterType((*DeleteResponse)(nil), "xmc.srv.core.task.DeleteResponse")
	proto.RegisterType((*SearchRequest)(nil), "xmc.srv.core.task.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "xmc.srv.core.task.SearchResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for TaskService service

type TaskServiceClient interface {
	Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error)
	Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error)
	Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error)
	Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type taskServiceClient struct {
	c           client.Client
	serviceName string
}

func NewTaskServiceClient(serviceName string, c client.Client) TaskServiceClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "xmc.srv.core.task"
	}
	return &taskServiceClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *taskServiceClient) Create(ctx context.Context, in *CreateRequest, opts ...client.CallOption) (*CreateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Create", in)
	out := new(CreateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Read(ctx context.Context, in *ReadRequest, opts ...client.CallOption) (*ReadResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Read", in)
	out := new(ReadResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Get(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*GetResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Get", in)
	out := new(GetResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*UpdateResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Update", in)
	out := new(UpdateResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...client.CallOption) (*DeleteResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Delete", in)
	out := new(DeleteResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *taskServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "TaskService.Search", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for TaskService service

type TaskServiceHandler interface {
	Create(context.Context, *CreateRequest, *CreateResponse) error
	Read(context.Context, *ReadRequest, *ReadResponse) error
	Get(context.Context, *GetRequest, *GetResponse) error
	Update(context.Context, *UpdateRequest, *UpdateResponse) error
	Delete(context.Context, *DeleteRequest, *DeleteResponse) error
	Search(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterTaskServiceHandler(s server.Server, hdlr TaskServiceHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&TaskService{hdlr}, opts...))
}

type TaskService struct {
	TaskServiceHandler
}

func (h *TaskService) Create(ctx context.Context, in *CreateRequest, out *CreateResponse) error {
	return h.TaskServiceHandler.Create(ctx, in, out)
}

func (h *TaskService) Read(ctx context.Context, in *ReadRequest, out *ReadResponse) error {
	return h.TaskServiceHandler.Read(ctx, in, out)
}

func (h *TaskService) Get(ctx context.Context, in *GetRequest, out *GetResponse) error {
	return h.TaskServiceHandler.Get(ctx, in, out)
}

func (h *TaskService) Update(ctx context.Context, in *UpdateRequest, out *UpdateResponse) error {
	return h.TaskServiceHandler.Update(ctx, in, out)
}

func (h *TaskService) Delete(ctx context.Context, in *DeleteRequest, out *DeleteResponse) error {
	return h.TaskServiceHandler.Delete(ctx, in, out)
}

func (h *TaskService) Search(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.TaskServiceHandler.Search(ctx, in, out)
}

func init() {
	proto.RegisterFile("github.com/xmc-dev/xmc/xmc-core/proto/task/task.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xad, 0x1b, 0xc7, 0x69, 0xc7, 0x75, 0x04, 0xab, 0x8a, 0x5a, 0x91, 0xda, 0x1a, 0x9f, 0x90,
	0x50, 0x5d, 0x51, 0xc4, 0x05, 0xb8, 0xf0, 0xa1, 0x56, 0x91, 0x40, 0x95, 0x5c, 0xb8, 0x70, 0xa9,
	0x5c, 0x7b, 0xda, 0xae, 0x6a, 0xc7, 0xc6, 0xbb, 0x89, 0xfa, 0x1b, 0xf9, 0x1d, 0x1c, 0xf9, 0x09,
	0x1c, 0xd0, 0xce, 0xda, 0x69, 0x9c, 0x38, 0x81, 0x96, 0x4b, 0xe2, 0x9d, 0xf7, 0xf6, 0x39, 0xf3,
	0xf6, 0xcd, 0x06, 0x5e, 0x5d, 0x71, 0x79, 0x3d, 0xbe, 0x08, 0xe2, 0x3c, 0x3b, 0xbc, 0xcd, 0xe2,
	0x83, 0x04, 0x27, 0xea, 0x9b, 0x9e, 0xe3, 0xbc, 0xc4, 0xc3, 0xa2, 0xcc, 0x65, 0x7e, 0x28, 0x23,
	0x71, 0x43, 0x1f, 0x01, 0xad, 0xd9, 0xe3, 0xdb, 0x2c, 0x0e, 0x44, 0x39, 0x09, 0x14, 0x27, 0x50,
	0xc0, 0xe0, 0xdd, 0xbf, 0x29, 0x09, 0x8c, 0xca, 0xf8, 0x3a, 0x43, 0x19, 0xcd, 0x3c, 0x6a, 0x55,
	0xff, 0xb7, 0x01, 0xe6, 0x97, 0x48, 0xdc, 0xb0, 0x3e, 0xac, 0xf3, 0xc4, 0x35, 0x3c, 0xe3, 0xd9,
	0x66, 0xb8, 0xce, 0x13, 0xb6, 0x0b, 0x90, 0x44, 0x32, 0x12, 0x28, 0xcf, 0x79, 0xe2, 0xae, 0x53,
	0x7d, 0xb3, 0xaa, 0x0c, 0x13, 0xc6, 0xc0, 0x1c, 0x45, 0x19, 0xba, 0x26, 0x01, 0xf4, 0xcc, 0x3c,
	0xb0, 0x13, 0x14, 0x71, 0xc9, 0x0b, 0xc9, 0xf3, 0x91, 0xdb, 0x21, 0x68, 0xb6, 0xa4, 0x44, 0xf9,
	0xa8, 0x18, 0xcb, 0xf3, 0x4b, 0x9e, 0xa2, 0xdb, 0xd5, 0xa2, 0x54, 0x39, 0xe6, 0x29, 0xb2, 0x7d,
	0xb0, 0xf3, 0xb1, 0x9c, 0xe2, 0x16, 0xe1, 0xa0, 0x4b, 0x44, 0xd8, 0x81, 0x5e, 0x11, 0x5d, 0xa1,
	0xfa, 0x45, 0x3d, 0x02, 0x2d, 0xb5, 0x1c, 0x26, 0x6c, 0x1b, 0xba, 0x92, 0xcb, 0x14, 0xdd, 0x0d,
	0x2a, 0xeb, 0x05, 0xf3, 0x60, 0x4b, 0xf9, 0x74, 0x9e, 0x72, 0x41, 0x5d, 0x6c, 0x6a, 0x41, 0x55,
	0xfb, 0xc4, 0x85, 0x1c, 0x26, 0xfe, 0x5b, 0x70, 0x3e, 0x94, 0x18, 0x49, 0x0c, 0xf1, 0xfb, 0x18,
	0x85, 0x64, 0xcf, 0xc1, 0x54, 0x30, 0x19, 0x61, 0x1f, 0xed, 0x04, 0x0b, 0xa6, 0x07, 0xca, 0xad,
	0x90, 0x48, 0xbe, 0x07, 0xfd, 0x7a, 0xb7, 0x28, 0xf2, 0x91, 0xc0, 0x79, 0x17, 0xfd, 0x5d, 0xb0,
	0x43, 0x8c, 0x92, 0x5a, 0x7d, 0x1e, 0x7e, 0x03, 0x5b, 0x1a, 0xae, 0xb6, 0xdf, 0xf3, 0xed, 0x70,
	0x82, 0xb2, 0x96, 0xae, 0x0f, 0xc4, 0xb8, 0x3b, 0x10, 0xff, 0x35, 0xd8, 0xc4, 0x78, 0x88, 0xfa,
	0x2f, 0x03, 0x9c, 0xaf, 0x45, 0x32, 0x63, 0xcd, 0x3d, 0x13, 0xf2, 0xf7, 0x34, 0xb4, 0x65, 0xe8,
	0x7f, 0x13, 0x32, 0x0d, 0x42, 0x6f, 0x55, 0x10, 0x36, 0x16, 0x82, 0xf0, 0x08, 0xfa, 0x75, 0xb7,
	0xda, 0x2d, 0x7f, 0x1f, 0x9c, 0x8f, 0x98, 0xe2, 0xd2, 0xfe, 0xd5, 0x96, 0x9a, 0x50, 0x6d, 0xf9,
	0x61, 0x80, 0x73, 0x46, 0x13, 0x56, 0xef, 0xd9, 0x86, 0x6e, 0xca, 0x33, 0x2e, 0x69, 0x9b, 0x13,
	0xea, 0x05, 0x7b, 0x02, 0x56, 0x7e, 0x79, 0x29, 0x50, 0x92, 0x6b, 0x4e, 0x58, 0xad, 0xe6, 0x1c,
	0xed, 0x3c, 0x60, 0xe6, 0xba, 0x8b, 0x2e, 0x4f, 0x1d, 0xb1, 0x56, 0x39, 0xd2, 0x5b, 0x70, 0xa4,
	0x84, 0x7e, 0xdd, 0x4b, 0x95, 0x9f, 0x03, 0xe8, 0x2a, 0x5c, 0xb8, 0x86, 0xd7, 0x59, 0x15, 0x20,
	0xcd, 0x62, 0x2f, 0xc0, 0x54, 0x17, 0x0d, 0xf5, 0x68, 0x1f, 0xed, 0x36, 0xd9, 0x33, 0x17, 0xd1,
	0x67, 0x94, 0x51, 0x48, 0xd4, 0xa3, 0x9f, 0x1d, 0xb0, 0x95, 0xc4, 0x19, 0x96, 0x13, 0x1e, 0x23,
	0x3b, 0x05, 0x4b, 0x0f, 0x18, 0xf3, 0x5a, 0x5e, 0xd6, 0x98, 0xdc, 0xc1, 0xd3, 0x15, 0x8c, 0xea,
	0x7c, 0xd6, 0xd8, 0x10, 0x4c, 0x35, 0x70, 0x6c, 0xaf, 0x85, 0x3c, 0x33, 0xa8, 0x83, 0xfd, 0xa5,
	0xf8, 0x54, 0xea, 0x18, 0x3a, 0x27, 0xea, 0xcc, 0x5a, 0x98, 0x77, 0x63, 0x39, 0xd8, 0x5b, 0x06,
	0x4f, 0x75, 0x4e, 0xc1, 0xd2, 0xc9, 0x6b, 0xed, 0xb1, 0x31, 0x82, 0xad, 0x3d, 0xce, 0xc5, 0x96,
	0x04, 0x75, 0x2e, 0x5b, 0x05, 0x1b, 0x99, 0x6e, 0x15, 0x9c, 0x0b, 0x35, 0x09, 0xea, 0x24, 0xb4,
	0x0a, 0x36, 0x02, 0xdf, 0x2a, 0xd8, 0x8c, 0x91, 0xbf, 0xf6, 0xde, 0xfa, 0x46, 0x77, 0xcc, 0x85,
	0x45, 0xff, 0x41, 0x2f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0xcd, 0x9e, 0xbd, 0x0b, 0x12, 0x07,
	0x00, 0x00,
}
